name: Linha de montagem 

on: 
  push: 
     branches: { main }

     jobs:
       build-e-teste:
         runs-on: ubuntu-latest 

         steps: 
         - name: 1. pegar o chassi do carro (código fonte)
         users: action/checkout@v4 

         - name: 2. estaçao de build (montagem)
         run: echo "construindo o projeto" 

         - name: 3. estaçao de teste 
         run: echo "rodando teste"

         


         
